### ISSUE TITLE
Recovered GetListeners from interface conversion: interface {} is nil, not bool: goroutine 27 [running]:

### ISSUE THREAD

**Issue by maheshb15** [tak2siva/Envoy-xDS-Example-From-File#1]
Hi,

   We are trying to publish below LDS.yaml to envoy, However we are getting below error and the pilot is crashing. COuld you please help to fix this
----------------------------------------------------
- name: listener_0
  address:
    socket_address: { address: 0.0.0.0, port_value: 80 }
  filter_chains:
  - filters:
    - name: envoy.http_connection_manager
      config:
        upgrade_configs:
        - upgrade_type: websocket
        stat_prefix: ingress_http
        codec_type: auto
        route_config:
          name: local_route
          virtual_hosts:
          - name: app_public_service
            domains: ["*"]
            routes:
            - match: { prefix: "/" }
              route: { cluster: app_public_service }
            - match: { prefix: "/rtm" }
              route: { cluster: app_public_service }
          - name: keys_service
            domains: ["keys.local"]
            routes:
            - match: { prefix: "/" }
              route: { cluster: keys_service }
          - name: faq_service
            domains: ["faq.local"]
            routes:
            - match: { prefix: "/" }
              route: { cluster: faq_service }
          - name: ml_service
            domains: ["ml.local"]
            routes:
            - match: { prefix: "/" }
              route: { cluster: ml_service }
          - name: sandbox_service
            domains: ["sandbox.local:80"]
            routes:
            - match: { prefix: "/" }
              route: { cluster: sandbox_service }
          - name: es_service
            domains: ["es.local"]
            routes:
            - match: { prefix: "/" }
              route: { cluster: es_service }
          - name: rmq_admin_service
            domains: ["rmq.local:80"]
            routes:
            - match: { prefix: "/" }
              route: { cluster: rmq_admin_service }
        http_filters:
        - name: envoy.gzip
          config:
            compression_level: BEST
        - name: envoy.router
          config: {}
        - name: envoy.buffer
          config:
            max_request_bytes: 100000
            max_request_time: 36s
- name: listener_1
  address:
    socket_address: { address: 0.0.0.0, port_value: 1024 }
  filter_chains:
  - filters:
    - name: envoy.tcp_proxy
      config:
        stat_prefix: nlp
        cluster: nlp_service
- name: listener_2
  address:
    socket_address: { address: 0.0.0.0, port_value: 5672 }
  filter_chains:
  - filters:
    - name: envoy.tcp_proxy
      config:
        stat_prefix: rmq
        cluster: rmq_service
-----------------------------------

Error:
---------------------------------------
2019/03/29 11:44:45 /go/src/Envoy-Pilot/cmd/server/service/dispatchService.go:107: Received ACK 0c258afe-957f-4bc7-a534-949fb955fc03 from adstest-cluster/CDS/bif0ab8faihp9uj6n1vg
2019/03/29 11:44:45 /go/src/Envoy-Pilot/cmd/server/mapper/listenerMapper.go:420: *********************************
2019/03/29 11:44:45 /go/src/Envoy-Pilot/cmd/server/mapper/listenerMapper.go:421: Recovered GetListeners from interface conversion: interface {} is nil, not bool: goroutine 27 [running]:
runtime/debug.Stack(0xc4202e7150, 0x1, 0x1)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
Envoy-Pilot/cmd/server/mapper.(*ListenerMapper).GetListeners.func1(0xc4202e7c10)
        /go/src/Envoy-Pilot/cmd/server/mapper/listenerMapper.go:421 +0xb1
panic(0xb82b40, 0xc4201c5600)
        /usr/local/go/src/runtime/panic.go:502 +0x229
Envoy-Pilot/cmd/server/mapper.getBoolean(...)
        /go/src/Envoy-Pilot/cmd/server/mapper/common.go:51
Envoy-Pilot/cmd/server/mapper.buildHttpFilter(0xb2aea0, 0xc420317ca0, 0xc70322, 0xc, 0xc42032bb98)
        /go/src/Envoy-Pilot/cmd/server/mapper/listenerMapper.go:251 +0x586
Envoy-Pilot/cmd/server/mapper.buildHttpConnectionManager(0xc420329d70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/Envoy-Pilot/cmd/server/mapper/listenerMapper.go:289 +0x1ef
Envoy-Pilot/cmd/server/mapper.buildFilterChains(0xc42032ea50, 0x1, 0x1, 0xd, 0xc42032ba78, 0xc420338000, 0x200, 0x1f8)
        /go/src/Envoy-Pilot/cmd/server/mapper/listenerMapper.go:380 +0x1c5
Envoy-Pilot/cmd/server/mapper.(*ListenerMapper).GetListener(0x1142a28, 0xb75620, 0xc420329c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/Envoy-Pilot/cmd/server/mapper/listenerMapper.go:412 +0x1e5
Envoy-Pilot/cmd/server/mapper.(*ListenerMapper).GetListeners(0x1142a28, 0xc420310000, 0x942, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/Envoy-Pilot/cmd/server/mapper/listenerMapper.go:435 +0x192
Envoy-Pilot/cmd/server/mapper.(*ListenerMapper).GetResources(0x1142a28, 0xc420310000, 0x942, 0x942, 0xc4201c0660, 0x14, 0x401c0d, 0xc7254f)
        /go/src/Envoy-Pilot/cmd/server/mapper/listenerMapper.go:447 +0x5d
Envoy-Pilot/cmd/server/service.(*DispatchService).buildDiscoveryResponseFor(0xc4201aeca0, 0xc420260090, 0xc694f6, 0x3, 0xc42025ebf0)
        /go/src/Envoy-Pilot/cmd/server/service/dispatchService.go:48 +0xcf
Envoy-Pilot/cmd/server/service.(*DispatchService).dispatchData(0xc4201aeca0, 0xd00a40, 0xc4201c7140, 0x7f49250091e0, 0xc4202a14e0, 0xc4201c8720)
        /go/src/Envoy-Pilot/cmd/server/service/dispatchService.go:81 +0x183
created by Envoy-Pilot/cmd/server/service.(*RegisterService).RegisterEnvoy
        /go/src/Envoy-Pilot/cmd/server/service/registerService.go:47 +0x111

2019/03/29 11:44:45 /go/src/Envoy-Pilot/cmd/server/mapper/listenerMapper.go:422: *********************************
2019/03/29 11:44:45 /go/src/Envoy-Pilot/cmd/server/mapper/listenerMapper.go:449: Error parsing listener config
2019/03/29 11:44:45 /go/src/Envoy-Pilot/cmd/server/service/dispatchService.go:51: Unable to build discovery response for adstest-cluster/LDS/bif0ab8faihp9uj6n20g
2019/03/29 11:44:45 /go/src/Envoy-Pilot/cmd/server/service/dispatchService.go:52: interface conversion: interface {} is nil, not bool
2019/03/29 11:44:45 /go/src/Envoy-Pilot/cmd/server/service/dispatchService.go:83: Unable to dispatch for adstest-cluster/LDS/bif0ab8faihp9uj6n20g
panic: Unable to dispatch for adstest-cluster/LDS/bif0ab8faihp9uj6n20g

goroutine 27 [running]:
log.Panicf(0xc7ac46, 0x1a, 0xc4202e7f30, 0x1, 0x1)
        /usr/local/go/src/log/log.go:333 +0xda
Envoy-Pilot/cmd/server/service.(*DispatchService).dispatchData(0xc4201aeca0, 0xd00a40, 0xc4201c7140, 0x7f49250091e0, 0xc4202a14e0, 0xc4201c8720)
        /go/src/Envoy-Pilot/cmd/server/service/dispatchService.go:83 +0x238
created by Envoy-Pilot/cmd/server/service.(*RegisterService).RegisterEnvoy
        /go/src/Envoy-Pilot/cmd/server/service/registerService.go:47 +0x111
----------------------------

**Comment by tak2siva** [comment]
@maheshb15  `http_filters` is empty. You need to provide valid configuration. 
```
match: { prefix: "/" }
route: { cluster: rmq_admin_service }
http_filters:
```

**Comment by maheshb15** [comment]
Hi Siva,

  Thanks for the response,we have added http_filters as below still the same issue.
       http_filters:
        - name: envoy.router
          config: {}
        - name: envoy.buffer
          config:
            max_request_bytes: 100000
            max_request_time: 36s

Attached config files below for reference,

https://pastebin.com/xCVXJLZU - LDS.yaml
https://pastebin.com/uhiT5Bs5 - CDS.yaml

**Comment by tak2siva** [comment]
I see. As of now there is no mapping for `http_filters` other than `health_check` so it's a bug. 
Feel free to PR if you are interested.

**Comment by tak2siva** [comment]
@maheshb15 
I see. As of now there is no mapping for `http_filters` other than `health_check` so it's a bug.
Feel free to PR [Envoy-Pilot](https://github.com/tak2siva/Envoy-Pilot) if you are interested.
